baseURL = "https://ngtzewee.netlify.com/"
languageCode = "en-UK"
title = "Thoughts"
description = "a Blog by Ben"
config = "config.toml"
tags = ["blog", "sidebar", "SEO"]
theme = "onepress"
# Enter your tracking code to enable Google Analytics
googleAnalytics = " "
# Disable comments by leaving disqusShortname empty
disqusShortname = "your disqus shortname"
copyright = "Copyright © 2019, Jeremiah Succeed; all rights reserved."
canonifyURLS = true
paginate = 12

[params]
	author = "Benjamin"
  bio = "Fullstack web developer and Templates designer."
	logo = "/images/logo.png"
	avatar = "/images/onepress-author.png"
	opengraphImage = "/images/onepress-logo.jpg"
	enableRSS = true

	customCSS = false
        readMore = "Read Up"
    
    # Social
	twitter  = "https://twitter.com/username"
	github   = "https://github.com/username"
	facebook  = ""
        linkedin  = ""

    
    # Widget
    widgets = true
    
    # Author box and Share button
    authorCard = false 
    shareButton = true
    
    # Code highlighting with highlight.js
    highlightJS = true

# Taxonomies
[taxonomies]
    tag = "tags"
